services:
  - docker

# Default travis command
install:
  # - pip install -r requirements.txt
  - make dockerbuild

script:
  - make test

after_success:
  - echo "We passed! This is where we would deploy!"
  - echo $TEST_VAR

after_failure:
  - echo "Oh no... Something went wrong, DON'T DEPLOY!"
  - echo $TEST_VAR