services:
  - docker

install:
  - make dockerimage

script:
  - make test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then make deploy; fi

after_failure:
  - echo "Oh no... Something went wrong, DON'T DEPLOY!"