language: python

services:
  - docker

python:
  - "3.6"
  - "3.7"
  - "3.8"

# Default travis command
install:
  # - pip install -r requirements.txt
  - make dockerbuild

script:
  - make test

after_success:
  - echo "We passed! This is where we would deploy!"

after_failure:
  - echo "Oh no... Something went wrong, DON'T DEPLOY!"