services:
  - docker

# Default travis command
install:
  # - pip install -r requirements.txt
  - make dockerbuild

script:
  - make test

after_success:
  - make deploy

after_failure:
  - echo "Oh no... Something went wrong, DON'T DEPLOY!"